-- Lead data

-- Create realistic lead seed data
WITH org_info AS (SELECT id FROM organizations WHERE name = 'Acme')
INSERT INTO leads (
  organization_id, name, email, secondary_email, phone, secondary_phone, company, job_title,
  import_method, fit_score, interest, tags, notes,
  first_conversion_utm_source, first_conversion_utm_medium, first_conversion_utm_campaign, first_conversion_utm_content, first_conversion_utm_term,
  last_conversion_utm_source, last_conversion_utm_medium, last_conversion_utm_campaign, last_conversion_utm_content, last_conversion_utm_term,
  external_id, external_source,
  created_at, updated_at
) 
SELECT 
  org_info.id,
  lead_name, lead_email, lead_secondary_email, lead_phone, lead_secondary_phone, lead_company, lead_job_title,
  lead_import_method, lead_fit_score, lead_interest, lead_tags, lead_notes,
  lead_first_conversion_utm_source, lead_first_conversion_utm_medium, lead_first_conversion_utm_campaign, lead_first_conversion_utm_content, lead_first_conversion_utm_term,
  lead_last_conversion_utm_source, lead_last_conversion_utm_medium, lead_last_conversion_utm_campaign, lead_last_conversion_utm_content, lead_last_conversion_utm_term,
  lead_external_id, lead_external_source,
  lead_created_at, lead_updated_at
FROM org_info,
(VALUES 
  -- High-value leads (Fit Score A/B) - RD Station imports
  ('Maria Silva Santos', 'maria.silva@techcorp.com.br', null, '+55 (11) 99123-4567', null, 'TechCorp Brasil', 'Diretora de TI', 'webhook', 'A', 85, ARRAY['qualified', 'enterprise', 'tech-sector'], 'Highly interested in enterprise solution. Budget approved for Q4.', 'google', 'cpc', 'enterprise-demo', 'homepage', 'enterprise software', 'google', 'cpc', 'enterprise-demo', 'homepage', 'enterprise software', 'f47ac10b-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '15 days', NOW() - INTERVAL '10 days'),
  ('Carlos Eduardo Mendes', 'carlos.mendes@inovacorp.com', 'carlos.alt@inovacorp.com', '+55 (21) 98765-4321', '+55 (21) 99999-0000', 'InovaCorp Ltda', 'Gerente de Operações', 'webhook', 'A', 92, ARRAY['hot-lead', 'qualified', 'ready-to-buy'], 'Scheduled demo for next week. Very interested in automation features.', 'linkedin', 'referral', 'sales-outreach', 'profile-link', 'automation software', 'linkedin', 'referral', 'sales-outreach', 'profile-link', 'automation software', '6ba7b816-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '8 days', NOW() - INTERVAL '3 days'),
  ('Ana Paula Costa', 'ana.costa@megasolucoes.com.br', null, '+55 (31) 97654-3210', null, 'MegaSoluções S.A.', 'CEO', 'api', 'B', 78, ARRAY['executive', 'decision-maker', 'scaling'], 'Expanding operations, looking for scalable solutions.', 'partner-site', 'referral', 'partner-program', 'partner-page', 'scaling solutions', 'google', 'organic', 'partner-program', 'blog-post', 'scaling solutions', '6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '22 days', NOW() - INTERVAL '18 days'),
  ('Roberto Lima Silva', 'roberto.lima@digisystems.net', null, '+55 (41) 96543-2109', null, 'DigiSystems', 'CTO', 'webhook', 'B', 73, ARRAY['technical', 'decision-maker', 'downloaded-whitepaper'], 'Downloaded technical architecture whitepaper. Asking detailed implementation questions.', 'google', 'organic', null, 'blog-post', 'system architecture', 'google', 'organic', null, 'blog-post', 'system architecture', '6ba7b811-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '18 days', NOW() - INTERVAL '12 days'),
  
  -- Medium-value leads (Fit Score C/D)
  ('Juliana Ferreira', 'juliana.ferreira@startupbr.co', 'juliana.personal@gmail.com', '+55 (85) 95432-1098', null, 'StartupBR', 'Fundadora', 'webhook', 'C', 45, ARRAY['startup', 'early-stage', 'budget-conscious'], 'Early-stage startup, interested but limited budget.', 'facebook', 'social', 'startup-event', 'booth-scan', 'startup tools', 'facebook', 'social', 'startup-event', 'booth-scan', 'startup tools', 'f47ac113-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '25 days', NOW() - INTERVAL '20 days'),
  ('Pedro Henrique Souza', 'pedro.souza@localtech.com.br', null, null, null, 'LocalTech Solutions', 'Desenvolvedor', 'import', 'C', 38, ARRAY['technical', 'small-company', 'evaluation'], 'Technical person evaluating solutions for small team.', 'direct', null, null, null, null, 'direct', null, null, null, null, null, null, NOW() - INTERVAL '30 days', NOW() - INTERVAL '25 days'),
  ('Fernanda Oliveira', 'fernanda.oliveira@consultoria.net', null, '+55 (62) 94321-0987', null, 'Consultoria Estratégica', 'Consultora Sênior', 'webhook', 'D', 25, ARRAY['consultant', 'multiple-clients', 'exploring'], 'Consultant exploring solutions for multiple clients.', 'linkedin', 'cpc', 'consultant-targeting', 'ad-carousel', 'business consulting', 'linkedin', 'cpc', 'consultant-targeting', 'ad-carousel', 'business consulting', 'f47ac10c-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '12 days', NOW() - INTERVAL '8 days'),
  ('Marcos Antonio Pereira', 'marcos.pereira@gmail.com', null, '+55 (47) 93210-9876', null, null, 'Freelancer', 'manual', 'D', 18, ARRAY['freelancer', 'individual', 'curious'], 'Individual freelancer curious about our platform.', 'google', 'organic', null, 'contact-form', 'freelance inquiry', 'google', 'organic', null, 'contact-form', 'freelance inquiry', null, null, NOW() - INTERVAL '5 days', NOW() - INTERVAL '2 days'),
  
  -- More leads for variety
  ('Cristina Rocha Andrade', 'cristina.andrade@grupobrasil.com', 'cristina.personal@outlook.com', '+55 (71) 92109-8765', '+55 (71) 88888-9999', 'Grupo Brasil Holdings', 'Diretora Financeira', 'webhook', 'A', 88, ARRAY['finance', 'enterprise', 'expansion'], 'CFO interested in cost reduction through automation.', 'email', 'campaign', 'cfo-newsletter', 'article-link', 'financial automation', 'linkedin', 'organic', 'cfo-newsletter', 'article-link', 'financial automation', 'f47ac10d-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '20 days', NOW() - INTERVAL '15 days'),
  ('João Carlos Ribeiro', 'joao.ribeiro@fabrica.ind.br', null, '+55 (51) 91098-7654', '+55 (51) 77777-8888', 'Fábrica Industrial', 'Gerente de Produção', 'api', 'B', 65, ARRAY['manufacturing', 'production', 'efficiency'], 'Manufacturing company looking to optimize production processes.', 'google', 'cpc', 'manufacturing-keywords', 'landing-page', 'production efficiency', 'google', 'cpc', 'manufacturing-keywords', 'landing-page', 'production efficiency', '6ba7b812-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '35 days', NOW() - INTERVAL '28 days'),
  ('Larissa Monteiro Silva', 'larissa.monteiro@ecommercepro.com.br', null, '+55 (81) 90987-6543', null, 'EcommercePro', 'Head de Growth', 'webhook', 'B', 82, ARRAY['ecommerce', 'growth', 'scaling', 'data-driven'], 'Growth hacker at fast-growing e-commerce company.', 'facebook', 'cpc', 'growth-hacking', 'ad-creative-a', 'ecommerce growth', 'facebook', 'cpc', 'growth-hacking', 'ad-creative-a', 'ecommerce growth', 'f47ac10e-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '14 days', NOW() - INTERVAL '9 days'),
  
  -- Additional leads with various characteristics
  ('Ricardo Nunes Oliveira', 'ricardo.nunes@agenciaweb.com', null, '+55 (27) 89876-5432', null, 'Agência Web Criativa', 'Sócio-Diretor', 'webhook', 'C', 52, ARRAY['agency', 'creative', 'client-services'], 'Digital agency owner looking for client management tools.', 'referral', 'word-of-mouth', null, null, null, 'referral', 'word-of-mouth', null, null, null, 'f47ac114-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '40 days', NOW() - INTERVAL '32 days'),
  ('Patrícia Moura Costa', 'patricia.moura@healthtech.med.br', null, '+55 (61) 88765-4321', null, 'HealthTech Solutions', 'Médica e Co-fundadora', 'webhook', 'A', 76, ARRAY['healthtech', 'medical', 'compliance', 'founder'], 'Medical doctor founding health tech startup, needs compliant solutions.', 'google', 'cpc', 'healthtech-demo', 'demo-form', 'hipaa compliant', 'google', 'cpc', 'healthtech-demo', 'demo-form', 'hipaa compliant', '6ba7b813-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '7 days', NOW() - INTERVAL '4 days'),
  ('Thiago Barbosa Alves', 'thiago.barbosa@logisticabr.com', null, null, null, 'Logística Brasil', 'Coordenador de TI', 'api', 'D', 31, ARRAY['logistics', 'it-coordinator', 'evaluation'], 'IT coordinator at logistics company, still in evaluation phase.', 'organic', 'search', null, null, null, 'organic', 'search', null, null, null, '6ba7b817-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '50 days', NOW() - INTERVAL '45 days'),
  ('Vanessa Santos Lima', 'vanessa.santos@retailchain.com.br', null, '+55 (11) 87654-3210', null, 'RetailChain Brasil', 'Gerente de Operações', 'webhook', 'C', 47, ARRAY['retail', 'operations', 'multi-location'], 'Operations manager at retail chain with multiple locations.', 'facebook', 'retargeting', 'retail-ops', 'dynamic-ad', 'retail management', 'facebook', 'retargeting', 'retail-ops', 'dynamic-ad', 'retail management', 'f47ac10f-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '28 days', NOW() - INTERVAL '21 days'),
  
  -- More diversity in lead profiles
  ('Eduardo Fernandes Cunha', 'eduardo.fernandes@fintech.startup', null, '+55 (21) 86543-2109', null, 'Fintech Innovation', 'Head de Produto', 'api', 'B', 69, ARRAY['fintech', 'product-manager', 'innovation'], 'Product manager at fintech startup, interested in user analytics.', 'producthunt', 'social', 'product-launch', 'ph-listing', 'user analytics', 'producthunt', 'social', 'product-launch', 'ph-listing', 'user analytics', '6ba7b814-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '16 days', NOW() - INTERVAL '11 days'),
  ('Gabriela Torres Marques', 'gabriela.torres@edtech.online', null, '+55 (85) 85432-1098', null, 'EdTech Online', 'Diretora Pedagógica', 'webhook', 'C', 41, ARRAY['edtech', 'education', 'pedagogy'], 'Educational director interested in learning analytics platform.', 'event', 'conference', 'edtech-summit', 'presentation-slide', 'learning analytics', 'event', 'conference', 'edtech-summit', 'presentation-slide', 'learning analytics', 'f47ac115-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '33 days', NOW() - INTERVAL '29 days'),
  ('Rafael Costa Pereira', 'rafael.costa@agroinovacao.agr.br', null, '+55 (77) 84321-0987', null, 'AgroInovação', 'Engenheiro Agrônomo', 'webhook', 'D', 29, ARRAY['agritech', 'agriculture', 'innovation'], 'Agricultural engineer exploring tech solutions for farming.', 'google', 'organic', null, 'blog-article', 'agtech innovation', 'google', 'organic', null, 'blog-article', 'agtech innovation', 'f47ac110-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '45 days', NOW() - INTERVAL '38 days'),
  
  -- Final batch for comprehensive coverage
  ('Isabela Rocha Mendes', 'isabela.rocha@proptech.imob', null, '+55 (31) 83210-9876', null, 'PropTech Imobiliária', 'Corretora Sênior', 'webhook', 'C', 56, ARRAY['proptech', 'real-estate', 'senior'], 'Senior real estate broker interested in property management tech.', 'instagram', 'social', 'realestate-content', 'story-swipe', 'property management', 'instagram', 'social', 'realestate-content', 'story-swipe', 'property management', 'f47ac111-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '19 days', NOW() - INTERVAL '14 days'),
  ('Daniel Souza Barbosa', 'daniel.souza@mobilidade.transport', null, null, null, 'Mobilidade Urbana', 'Analista de Dados', 'api', 'D', 22, ARRAY['mobility', 'data-analyst', 'urban-planning'], 'Data analyst working on urban mobility solutions.', 'github', 'referral', 'open-source', 'readme-link', 'mobility data', 'github', 'referral', 'open-source', 'readme-link', 'mobility data', '6ba7b818-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '42 days', NOW() - INTERVAL '35 days'),
  ('Camila Dias Rodrigues', 'camila.dias@socialimpact.org.br', null, '+55 (13) 82109-8765', null, 'Social Impact Brasil', 'Coordenadora de Projetos', 'manual', 'F', 15, ARRAY['ngo', 'social-impact', 'non-profit'], 'Project coordinator at NGO, limited budget but interested in social impact.', 'facebook', 'organic', null, 'nonprofit-page', 'social impact', 'facebook', 'organic', null, 'nonprofit-page', 'social impact', null, null, NOW() - INTERVAL '60 days', NOW() - INTERVAL '55 days'),
  
  -- International and remote leads
  ('Alessandro Martinez Santos', 'alessandro.martinez@remotework.global', null, '+55 (11) 81098-7654', null, 'Remote Work Global', 'Remote Team Lead', 'webhook', 'B', 71, ARRAY['remote-work', 'global-team', 'productivity'], 'Leading remote development team, interested in collaboration tools.', 'medium', 'content', 'remote-work-article', 'article-cta', 'remote productivity', 'medium', 'content', 'remote-work-article', 'article-cta', 'remote productivity', '6ba7b815-9dad-11d1-80b4-00c04fd430c8', 'hubspot', NOW() - INTERVAL '26 days', NOW() - INTERVAL '19 days'),
  ('Bianca Oliveira Cruz', 'bianca.oliveira@sustentavel.eco.br', null, '+55 (48) 80987-6543', null, 'Sustentável Eco', 'Especialista em ESG', 'webhook', 'C', 44, ARRAY['sustainability', 'esg', 'environmental'], 'ESG specialist at sustainability consulting firm.', 'linkedin', 'organic', null, 'event-post', 'sustainability tech', 'linkedin', 'organic', null, 'event-post', 'sustainability tech', 'f47ac116-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '37 days', NOW() - INTERVAL '30 days'),
  ('Felipe Machado Silva', 'felipe.machado@gamedev.studio', null, '+55 (41) 79876-5432', null, 'GameDev Studio', 'Game Designer', 'webhook', 'D', 27, ARRAY['gaming', 'creative', 'indie-dev'], 'Indie game developer exploring analytics for game metrics.', 'discord', 'community', 'gamedev-discussion', 'bot-link', 'game analytics', 'discord', 'community', 'gamedev-discussion', 'bot-link', 'game analytics', 'f47ac112-58cc-4372-a567-0e02b2c3d479', 'rd_station', NOW() - INTERVAL '21 days', NOW() - INTERVAL '17 days')
) AS lead_data(
  lead_name, lead_email, lead_secondary_email, lead_phone, lead_secondary_phone, lead_company, lead_job_title,
  lead_import_method, lead_fit_score, lead_interest, lead_tags, lead_notes,
  lead_first_conversion_utm_source, lead_first_conversion_utm_medium, lead_first_conversion_utm_campaign, lead_first_conversion_utm_content, lead_first_conversion_utm_term,
  lead_last_conversion_utm_source, lead_last_conversion_utm_medium, lead_last_conversion_utm_campaign, lead_last_conversion_utm_content, lead_last_conversion_utm_term,
  lead_external_id, lead_external_source,
  lead_created_at, lead_updated_at
);